
default_platform(:ios)
platform :ios do
  desc "pgy archive"
  lane :pgy do
    xcode_select("/Applications/Xcode.app")
    gym(xcargs: "-UseNewBuildSystem=YES",
        scheme: "TravisTest",
	project: "TravisTest.xcodeproj",
	export_method: "ad-hoc",
      	export_options: {
          compileBitcode: false,
        }  
     )
    pgyer(api_key: "92c0423f53102ddf1f06a92bd0f2fb86", user_key: "4ae6cbc1ef990ff47453be759d93d306",password: "123456", install_type: "2")

    # firim(firim_api_token:"392bc7f0f92622ec086cb47be760b054")
  end
end