
default_platform(:ios)
platform :ios do
  keychain_name = "ios-build.keychain"
  keychain_password = ENV["KEY_PASSWORD"]
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "300"
  ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

  create_keychain(
    name: keychain_name,
    password: keychain_password,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )

  import_certificate(
    certificate_path: ".travis/zsy-dis.p12",
    certificate_password: ENV["KEY_PASSWORD"],
    keychain_name: keychain_name,
    keychain_password: keychain_password
  )

  desc "fir archive"
  lane :fir do
    xcode_select("/Applications/Xcode.app")
    app_identifier="com.zsy.travistest"
    update_app_identifier(
      xcodeproj: "TravisTest.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "TravisTest/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: "com.zsy.travistest" # The App Identifier
    )
    disable_automatic_code_signing(
      path: "TravisTest.xcodeproj"
    )
    update_project_provisioning(
      xcodeproj: "TravisTest.xcodeproj",
      profile: ".travis/comzsytravistest_AdHoc.mobileprovision", # optional if you use sigh
      target_filter: "TravisTest", # matches name or type of a target
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution" # optionally specify the codesigning identity
    )
    gym(clean:true, #打包前clean项目
    	# output_directory: "./firim",#ipa的存放目录
	scheme: "TravisTest",
	project: "TravisTest.xcodeproj",
        # workspace: "RxswiftStudy.xcworkspace",
	export_method: "ad-hoc",
      	export_options: {
          compileBitcode: false
        }  
     )
    pgyer(api_key: "92c0423f53102ddf1f06a92bd0f2fb86", user_key: "4ae6cbc1ef990ff47453be759d93d306",password: "123456", install_type: "2")

    # firim(firim_api_token:"392bc7f0f92622ec086cb47be760b054")
  end
end